= Commons Compress

[quote, https://commons.apache.org/proper/commons-compress/]
https://commons.apache.org/proper/commons-compress/[The Apache Commons Compress] library defines an API for working with ar, cpio, Unix dump, tar, zip, gzip, XZ, Pack200, bzip2, 7z, arj, lzma, snappy, DEFLATE, lz4, Brotli, Zstandard, DEFLATE64 and Z files.

== Compress Plugins

This chapter describes all the plugins contained in the `compress-plugin` module.

=== `io.freefair.compress`
This plugin applies all of the plugins listed below for convenience.

=== `io.freefair.compress.trees`

This plugin adds the `commonsCompress` Extension to the project, which provides the  following methods:

[source, java]
----
FileTree arTree(Object arFile);

FileTree arjTree(Object arjFile);
FileTree arjTree(Object arjFile, String charsetName);

FileTree cpioTree(Object cpioFile);
FileTree cpioTree(Object cpioFile, String encoding);
FileTree cpioTree(Object cpioFile, int blockSize);
FileTree cpioTree(Object cpioFile, int blockSize, String encoding);

FileTree sevenZipTree(Object sevenZipFile);
FileTree sevenZipTree(Object sevenZipFile, char[] password);

FileTree dumpTree(Object dumpFile);
FileTree dumpTree(Object dumpFile, String encoding);
----

These methods can be used to open `ar`, `arj`, `cpio`, `7z` or `dump` archives.
They work the same way as the
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:zipTree(java.lang.Object)[`zipTree`]
and
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:tarTree(java.lang.Object)[`tarTree`]
methods which are described https://docs.gradle.org/current/userguide/working_with_files.html#sec:unpacking_archives_example[here]

.Example
[source,groovy]
----
task example(type: Sync) {
    from commonsCompress.arTree(file("foo.ar"))
}
----

=== `io.freefair.compress.ar`

This plugin makes the <<Ar>> task available without it's qualified name.

=== `io.freefair.compress.cpio`

This plugin makes the <<Cpio>> task available without it's qualified name.

=== `io.freefair.compress.7z`

This plugin makes the <<SevenZip>> task available without it's qualified name.

== Compress Tasks

[#Ar]
=== `Ar`

This
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html[`AbstractArchiveTask`]
implementation can be used to create `ar` archives.

[source, groovy]
----
task packageArArchive(type: io.freefair.gradle.plugins.compress.tasks.Ar) {
    archiveFileName = "my-distribution.ar"
    destinationDirectory = file("$buildDir/dist")

    from "$buildDir/toArchive"

    longFileMode = org.apache.commons.compress.archivers.ar.ArArchiveOutputStream.LONGFILE_ERROR
}
----

[#BZip2]
=== `BZip2`

This task can be used to compress individual files using BZip2.

[source, groovy]
----
task compressBZip2(type: io.freefair.gradle.plugins.compress.tasks.BZip2) {
    source "src/main/resources"
    destinationDir = file("$buildDir/compressed")
    fileExtension = "bz2"
}
----

[#Cpio]
=== `Cpio`

This
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html[`AbstractArchiveTask`]
implementation can be used to create `cpio` archives.

[source, groovy]
----
task packageCpioArchive(type: io.freefair.gradle.plugins.compress.tasks.Cpio) {
    archiveFileName = "my-distribution.cpio"
    destinationDirectory = file("$buildDir/dist")

    from "$buildDir/toArchive"

    format = org.apache.commons.compress.archivers.cpio.CpioConstants.FORMAT_NEW
    blockSize = 512
    encoding = "US-ASCII"
}
----

[#Deflate]
=== `Deflate`

This task can be used to compress individual files using the zlib deflate algorithm.

[source, groovy]
----
task compressDeflate(type: io.freefair.gradle.plugins.compress.tasks.Deflate) {
    source "src/main/resources"
    destinationDir = file("$buildDir/compressed")
    fileExtension = "deflate"

    compressionLevel = 9
    withZlibHeader = false
}
----

[#GZip]
=== `GZip`

This task can be used to compress individual files using BZip2.

[source, groovy]
----
task compressGZip(type: io.freefair.gradle.plugins.compress.tasks.GZip) {
    source "src/main/resources"
    destinationDir = file("$buildDir/compressed")
    fileExtension = "gz"

    compressionLevel = 9
    comment = ""
    addFilename = false
}
----

[#LZMA]
=== `LZMA`

This task can be used to compress individual files using LZMA.

[source, groovy]
----
task compressLZMA(type: io.freefair.gradle.plugins.compress.tasks.LZMA) {
    source "src/main/resources"
    destinationDir = file("$buildDir/compressed")
    fileExtension = "lzma"
}
----

[#SevenZip]
=== `SevenZip`

This
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html[`AbstractArchiveTask`]
implementation can be used to create `7z` archives.

[source, groovy]
----
task packageSevenZipArchive(type: io.freefair.gradle.plugins.compress.tasks.SevenZip) {
    archiveFileName = "my-distribution.7z"
    destinationDirectory = file("$buildDir/dist")

    from "$buildDir/toArchive"

    contentCompression = org.apache.commons.compress.archivers.sevenz.SevenZMethod.LZMA2
}
----
