= Lombok

[quote, https://projectlombok.org]
https://projectlombok.org/[Project Lombok] is a java library that automatically plugs into your editor and build tools, spicing up your java.
Never write another getter or equals method again, with one annotation your class has a fully featured builder, Automate your logging variables, and much more.

== Lombok Plugins

This chapter describes all the plugins contained in the `lombok-plugin` module.

=== `io.freefair.lombok-base`

This plugin adds the `lombok` configuration and the `lombok` extension to the project.
It also configures all Lombok related tasks to use the `lombok` configuration.

The used Lombok version can be customized using the `lombok` extension:

.Setting a custom Lombok version
[source,groovy]
----
lombok {
    version = "1.18.24"
}
----

=== `io.freefair.lombok`

This plugin simplifies the use of https://projectlombok.org/[Lombok] in Gradle by performing the following steps:

- Lombok is added to the `annotationProcessor` and `compileOnly` configurations of each source set
- For each source set a `delombok` task is created.
- The `javadoc` task will be configured to read the delombok-ed sources instead of the actual sources.
- `lombok-mapstruct-binding` is added to each source-set when 'org.mapstruct:mapstruct-processor' is found.
- The compile tasks for each source set will consider the `lombok.config`(s) in their up-to-date checks

[NOTE]
====
Only the default `javadoc` https://docs.gradle.org/{gradle_version}/dsl/org.gradle.api.tasks.javadoc.Javadoc.html[Javadoc] task will be modified to work on the delombok-ed sources.
If you create your own custom https://docs.gradle.org/{gradle_version}/dsl/org.gradle.api.tasks.javadoc.Javadoc.html[Javadoc] tasks, it's up to you to assign the correct `source`.
The `delombok` task created by this plugin can be used as source for the javadoc task:
[source,groovy]
----
task myJavadocs(type: Javadoc) {
  source = delombok
}
----
====

[NOTE]
====
In contrast to the `javadoc` task, the `sourcesJar` task is *not* adjusted to use the delomboked sources.
This is done on purpose, so the line numbers in the `-sources.jar` match the `LineNumberTable` in the generated class files.
====

== Lombok Tasks

The following task are provided:

- link:../api/io/freefair/gradle/plugins/lombok/tasks/Delombok.html[`io.freefair.gradle.plugins.lombok.tasks.Delombok`]
- link:../api/io/freefair/gradle/plugins/lombok/tasks/LombokApiJar.html[`io.freefair.gradle.plugins.lombok.tasks.LombokApiJar`]
- link:../api/io/freefair/gradle/plugins/lombok/tasks/LombokRuntimeJar.html[`io.freefair.gradle.plugins.lombok.tasks.LombokRuntimeJar`]
- link:../api/io/freefair/gradle/plugins/lombok/tasks/PostCompile.html[`io.freefair.gradle.plugins.lombok.tasks.PostCompile`]
- link:../api/io/freefair/gradle/plugins/lombok/tasks/LombokConfig.html[`io.freefair.gradle.plugins.lombok.tasks.LombokConfig`]
