= Commons Compress Plugins

== `io.freefair.compress`
This plugin applies all of the plugins listed below for convenience.

== `io.freefair.compress.trees`

This plugin adds the following methods to the project:

[source, java]
----
FileTree arTree(Object arFile);

FileTree arjTree(Object arjFile);
FileTree arjTree(Object arjFile, String charsetName);

FileTree cpioTree(Object cpioFile);
FileTree cpioTree(Object cpioFile, String encoding);
FileTree cpioTree(Object cpioFile, int blockSize);
FileTree cpioTree(Object cpioFile, int blockSize, String encoding);

FileTree sevenZipTree(Object sevenZipFile);
FileTree sevenZipTree(Object sevenZipFile, char[] password);

FileTree dumpTree(Object dumpFile);
FileTree dumpTree(Object dumpFile, String encoding);
----

These methods can be used to open `ar`, `arj`, `cpio`, `7z` or `dump` archives.
They work the same way as the
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:zipTree(java.lang.Object)[`zipTree`]
and
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:tarTree(java.lang.Object)[`tarTree`]
methods which are described https://docs.gradle.org/current/userguide/working_with_files.html#sec:unpacking_archives_example[here]

== `io.freefair.compress.ar`

This plugin makes the `io.freefair.gradle.plugins.compress.tasks.Ar` task available without it's qualified name.

[source, groovy]
----
task packageArArchive(type: Ar) {
    archiveFileName = "my-distribution.ar"
    destinationDirectory = file("$buildDir/dist")

    from "$buildDir/toArchive"

    longFileMode = org.apache.commons.compress.archivers.ar.ArArchiveOutputStream.LONGFILE_ERROR
}
----

TIP: This task extends from https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html[`AbstractArchiveTask`], so you can use all of it's features.

== `io.freefair.compress.cpio`

This plugin makes the `io.freefair.gradle.plugins.compress.tasks.Cpio` task available without it's qualified name.

[source, groovy]
----
task packageCpioArchive(type: Cpio) {
    archiveFileName = "my-distribution.cpio"
    destinationDirectory = file("$buildDir/dist")

    from "$buildDir/toArchive"

    format = org.apache.commons.compress.archivers.cpio.CpioConstants.FORMAT_NEW
    blockSize = 512
    encoding = "US-ASCII"
}
----

TIP: This task extends from https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html[`AbstractArchiveTask`], so you can use all of it's features.

== `io.freefair.compress.7z`

This plugin makes the `io.freefair.gradle.plugins.compress.tasks.SevenZip` task available without it's qualified name.

[source, groovy]
----
task packageSevenZipArchive(type: SevenZip) {
    archiveFileName = "my-distribution.7z"
    destinationDirectory = file("$buildDir/dist")

    from "$buildDir/toArchive"

    contentCompression = org.apache.commons.compress.archivers.sevenz.SevenZMethod.LZMA2
}
----

TIP: This task extends from https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html[`AbstractArchiveTask`], so you can use all of it's features.
