/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'larsgrefer' at '30.12.15 19:06' with Gradle 2.10
 *
 * @author larsgrefer, @date 30.12.15 19:06
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
