= AspectJ

[quote, https://www.eclipse.org/aspectj/]
____
*https://www.eclipse.org/aspectj/[AspectJ™] is*

- a seamless aspect-oriented extension to the Java™ programming language
- Java platform compatible
- easy to learn and use

*AspectJ™ enables*

- clean modularization of crosscutting concerns, such as error checking and handling, synchronization, context-sensitive behavior, performance optimizations, monitoring and logging, debugging support, and multi-object protocols
____

== Getting Started

The FreeFair AspectJ plugins support two approaches: _compile-time weaving_ and _post-compile weaving_.
Choose the one that fits your project.

=== Quick Start: Compile-Time Weaving

Use this when your project only has Java and AspectJ sources and does not need javac-specific features like annotation processing with Lombok.

--
[source,groovy,subs=attributes+,role="primary"]
.Groovy
----
plugins {
    id "io.freefair.aspectj" version "{revnumber}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation "org.aspectj:aspectjrt:1.9.25.1"
}
----
[source,kotlin,subs=attributes+,role="secondary"]
.Kotlin
----
plugins {
    id("io.freefair.aspectj") version "{revnumber}"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    implementation("org.aspectj:aspectjrt:1.9.25.1")
}
----
--

Place your aspects in `src/main/aspectj/` (`.aj` files) or use `@Aspect`-annotated Java classes in `src/main/java/`.
The plugin disables the standard `compileJava` task and compiles both directories with `ajc`.

[source,bash]
----
./gradlew compileAspectj
----

=== Quick Start: Post-Compile Weaving

Use this when you need AspectJ together with annotation processors (e.g., Lombok), or with Kotlin, Groovy, or Scala sources.

--
[source,groovy,subs=attributes+,role="primary"]
.Groovy
----
plugins {
    id "java"
    id "io.freefair.aspectj.post-compile-weaving" version "{revnumber}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation "org.aspectj:aspectjrt:1.9.25.1"
}
----
[source,kotlin,subs=attributes+,role="secondary"]
.Kotlin
----
plugins {
    java
    id("io.freefair.aspectj.post-compile-weaving") version "{revnumber}"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    implementation("org.aspectj:aspectjrt:1.9.25.1")
}
----
--

Your source code is compiled by `javac` first, then `ajc` weaves aspects into the resulting bytecode.
Write your aspects as `@Aspect`-annotated classes in `src/main/java/`.

NOTE: Post-compile weaving only supports pre-compiled aspects (annotation-based `@Aspect` classes or aspects provided as bytecode on the aspectpath). Native `.aj` source files require compile-time weaving.

[source,bash]
----
./gradlew compileJava
----

TIP: For complete working examples (including multi-module setups with separate aspect libraries), see the https://github.com/freefair/gradle-plugins/tree/main/examples/aspectj[aspectj example projects].

== AspectJ Plugins

The `aspectj-plugin` module provides the following plugins.
They implement _compile-time weaving_ and _post-compile weaving_ respectively.

=== Compile-time weaving

When using compile-time weaving, your sources are directly compiled by `ajc`.
This works well for simple projects which only have `.java` and `.aj` sources and don't need javac-specific features like annotation processing with Project Lombok.

The `io.freefair.aspectj` plugin is built analogous to the existing plugins for Groovy, Scala and Kotlin.
It adds an additional `aspectj` directory to every source set which will be compiled by `ajc`.
This creates the additional source folders  `src/main/aspectj`, `src/test/aspectj` and so forth.

In order to avoid conflicts and confusion between ajc and javac, the default `compile*Java` tasks will be disabled,
and `src/<sourceSet>/java` will be compiled by ajc as well.
This aligns with the AspectJ Maven Plugin, which also uses `src/<sourceSet>/java`.

[NOTE]
====
Technically, each Gradle https://docs.gradle.org/{gradle_version}/dsl/org.gradle.api.tasks.SourceSet.html[SourceSet] will get two new https://docs.gradle.org/{gradle_version}/dsl/org.gradle.api.file.SourceDirectorySet.html[SourceDirectorySets]: `aspectj` and `allAspectj`.

`aspectj` contains `src/<sourceSet>/aspectj` while `allAspectj` combines `aspectj` with the default `java` SourceDirectorySet.

The `compile*Aspectj` tasks the use `allAspectj` as its source, in order to compile both `src/<sourceSet>/aspectj` and `src/<sourceSet>/java`

If you need both ajc and javac, just reenable the `compile*Java` tasks and switch the `compile*AspectJ` tasks from `allAspectj` to `aspectj`.
====

=== Post-compile weaving

The `io.freefair.aspectj.post-compile-weaving` enhances the
`compileJava` (`compileGroovy`, `compileScala`, `compileKotlin`) tasks of all source sets
with an additional `ajc` action in order to perform post-compile weaving.

With this setup, your source code is first compiled by javac, groovyc, scalac and/or kotlinc as usual.
The resulting byte-code is then post-processed by ajc.
This enables the usage of AspectJ in combination with annotation processors like Lombok or even other Languages like Groovy, Scala and Kotlin.

=== Configuration Options

==== AspectJ Runtime

--
[source, groovy, role="primary"]
.Groovy
----
dependencies {
    implementation "org.aspectj:aspectjrt:1.9.21.1"
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
dependencies {
    implementation("org.aspectj:aspectjrt:1.9.21.1")
}
----
--

==== Aspectpath

Additional advices (the `-aspectpath`) can be declared as dependencies of the `aspect` configuration:

--
[source, groovy, role="primary"]
.Groovy
----
dependencies {
    aspect project(":my-aspect")
    testAspect "com.example.foo:bar-aspect:1.0.0"
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
dependencies {
    aspect(project(":my-aspect"))
    testAspect("com.example.foo:bar-aspect:1.0.0")
}
----
--

==== Inpath

Additional jars/classes which should be woven and added to the output as well (the `-inpath`)
can be declared as dependencies fo the `inpath` configuration:

--
[source, groovy, role="primary"]
.Groovy
----
dependencies {
    inpath project(":my-lib")
    testInpath "com.example.foo:bar-lib:1.0.0"
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
dependencies {
    inpath(project(":my-lib"))
    testInpath("com.example.foo:bar-lib:1.0.0")
}
----
--

==== `io.freefair.aspectj.post-compile-weaving`

This plugin enhances the `compileJava` (`compileGroovy`, `compileScala`, `compileKotlin`) tasks of all source sets
with an additional `ajc` action in order to perform post-compile-weaving.

The output of the compilation (`javac`, etc.) becomes the `-inpath` for `ajc`.

The `-classpath`, `-source` and `-target`
arguments of `ajc` are set automatically to the corresponding values taken from the compile task.
Additional `ajc` arguments can be configured using the `ajc.options.compilerArgs` property as shown below.

The following things are configurable:

--
[source, groovy, role="primary"]
.Groovy
----
compileJava {
    ajc {
        enabled = true //<1>
        classpath //<2>
        options {
            aspectpath.setFrom configurations.aspect //<3>
            compilerArgs = [] //<4>
        }
    }
}
compileTestJava {
    ajc {
        enabled = true //<1>
        classpath //<2>
        options {
            aspectpath.setFrom configurations.testAspect //<3>
            compilerArgs = [] //<4>
        }
    }
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
tasks.compileJava {
    configure<AjcAction> {
        enabled = true //<1>
        classpath //<2>
        options {
            aspectpath.setFrom(configurations.aspect) //<3>
            compilerArgs = listOf("") //<4>
        }
    }
}
tasks.compileTestJava {
    configure<AjcAction> {
        enabled = true //<1>
        classpath //<2>
        options {
            aspectpath.setFrom(configurations.testAspect) //<3>
            compilerArgs = listOf("") //<4>
        }
    }
}
----
--
<1> Specifies if ajc should run at all. Defaults to `true`
<2> The classpath containing ajc itself (`aspectjtools.jar`). Inferred from the compile/runtime classpaths by default.
<3> The classpath containing additional advices to weave. This directly maps to the `-aspectpath` argument of ajc.
<4> Addittional arguments which will be passed to `ajc`.

NOTE: The official documentation of `ajc` can be found here: https://www.eclipse.org/aspectj/doc/released/devguide/ajc-ref.html

== AspectJ Tasks

=== `AspectjCompile`

This
https://docs.gradle.org/{gradle_version}/javadoc/org/gradle/api/tasks/compile/AbstractCompile.html[`AbstractCompile`]
task can be used to run
https://www.eclipse.org/aspectj/doc/released/devguide/ajc-ref.html[`ajc`].

--
[source, groovy, role="primary"]
.Groovy
----
task myAjcTask(type: io.freefair.gradle.plugins.aspectj.AspectjCompile) {
    aspectjClasspath.setFrom configurations.aspectj
    ajcOptions {
        inpath = files()
        aspectpath = files()
    }
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
tasks.register<AspectjCompile>("myAjcTask") {
    aspectjClasspath.setFrom(configurations.aspectj)
    ajcOptions {
        inpath = files()
        aspectpath = files()
    }
}
----
--
