= Embedded Sass

- https://github.com/larsgrefer/dart-sass-java
- https://github.com/sass/embedded-protocol
- https://github.com/sass/dart-sass-embedded

== Getting Started

The Embedded Sass plugins compile https://sass-lang.com/[Sass/SCSS] files to CSS using the https://github.com/larsgrefer/dart-sass-java[Dart Sass] embedded compiler.
Choose the plugin variant that matches your project type.

=== For Java / Resource Projects

Place `.scss` files in `src/main/resources/`.
The compiled CSS is included in the processed resources automatically.

--
[source,groovy,subs=attributes+,role="primary"]
.Groovy
----
plugins {
    id "java"
    id "io.freefair.sass-java" version "{revnumber}"
}
----
[source,kotlin,subs=attributes+,role="secondary"]
.Kotlin
----
plugins {
    java
    id("io.freefair.sass-java") version "{revnumber}"
}
----
--

.src/main/resources/styles/main.scss
[source,scss]
----
$primary: #3366cc;

body {
  font-family: system-ui, sans-serif;

  a {
    color: $primary;

    &:hover {
      color: darken($primary, 15%);
    }
  }
}
----

[source,bash]
----
./gradlew compileSass
----

The compiled CSS appears in `build/sass/main/` and is included in `processResources` output.

=== For WAR Projects

Place `.scss` files in `src/main/webapp/`.

--
[source,groovy,subs=attributes+,role="primary"]
.Groovy
----
plugins {
    id "war"
    id "io.freefair.sass-war" version "{revnumber}"
}
----
[source,kotlin,subs=attributes+,role="secondary"]
.Kotlin
----
plugins {
    war
    id("io.freefair.sass-war") version "{revnumber}"
}
----
--

[source,bash]
----
./gradlew compileWebappSass
----

TIP: For complete working examples (Java resources, WAR, and WebJars integration), see the https://github.com/freefair/gradle-plugins/tree/main/examples/embedded-sass[embedded-sass example projects].

== Embedded Sass Plugins

The `embedded-sass-plugin` module provides the following plugins.

=== `io.freefair.sass-base`

This plugin adds the `sass` extension to the project and applies it to all `SassCompile` tasks.

--
[source, groovy, role="primary"]
.Groovy
----
sass {
    omitSourceMapUrl = false
    outputStyle = com.sass_lang.embedded_protocol.OutputStyle.EXPANDED
    sourceMapContents = false
    sourceMapEmbed = false
    sourceMapEnabled = true
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
sass {
    omitSourceMapUrl = false
    outputStyle = com.sass_lang.embedded_protocol.OutputStyle.EXPANDED
    sourceMapContents = false
    sourceMapEmbed = false
    sourceMapEnabled = true
}
----
--

=== `io.freefair.sass-webjars`

This plugin adds webjars support to the sass compilation:

--
[source, groovy, role="primary"]
.Groovy
----
dependencies {
    implementation 'org.webjars:bootstrap:5.1.3'
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
dependencies {
    implementation("org.webjars:bootstrap:5.1.3")
}
----
--

[source,scss]
----
@import "scss/bootstrap";
----

=== `io.freefair.sass-java`

This plugin configures a `compileSass` task for the
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html#org.gradle.api.tasks.SourceSet:resources[resources]
of each
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:sourceSets(groovy.lang.Closure)[source set].

=== `io.freefair.sass-war`

This plugin creates a `compileWebappSass` for the `src/main/webapp` folder of your `war` project.

== Sass Tasks
