= JaCoCo

[quote, https://www.eclemma.org/jacoco/]
https://www.eclemma.org/jacoco/[JaCoCo] is a free code coverage library for Java, which has been created by the EclEmma team based on the lessons learned from using and integration existing libraries for many years.

== JaCoCo Plugins

The `jacoco-plugin` module provides plugins for aggregating code coverage data across multi-project builds.

=== `io.freefair.aggregate-jacoco-report`

This plugin adds an `aggregateJacocoReport` task to the project it is applied to.
The task generates an aggregated JaCoCo report for the `main` source sets of all subprojects
by collecting the execution data from their test tasks.

Apply this plugin to the root project:

--
[source,groovy,subs=attributes+,role="primary"]
.Groovy
----
plugins {
    id "io.freefair.aggregate-jacoco-report" version "{revnumber}"
}
----
[source,kotlin,subs=attributes+,role="secondary"]
.Kotlin
----
plugins {
    id("io.freefair.aggregate-jacoco-report") version "{revnumber}"
}
----
--

[source,bash]
----
./gradlew aggregateJacocoReport
----

The aggregated report is of type https://docs.gradle.org/{gradle_version}/dsl/org.gradle.testing.jacoco.tasks.JacocoReport.html[JacocoReport].

TIP: For a multi-module example, see the https://github.com/freefair/gradle-plugins/tree/main/examples/jacoco[jacoco example project].

== JaCoCo Tasks

=== `JacocoDump`

The
link:../api/io/freefair/gradle/plugins/jacoco/tasks/JacocoDump.html[`io.freefair.gradle.plugins.jacoco.tasks.JacocoDump`]
task is the Gradle equivalent of the https://www.jacoco.org/jacoco/trunk/doc/ant.html#dump[`dump` Ant-Task].
It connects to a remote JaCoCo agent via TCP and downloads execution data.

.JacocoDump Example
--
[source, groovy, role="primary"]
.Groovy
----
task dump(type: io.freefair.gradle.plugins.jacoco.tasks.JacocoDump) {
    address = "localhost"
    port = 6300
    retryCount = 10
    dump = true
    reset = false
    destfile = file("build/dump.exec")
    append = true
}
----
[source, kotlin, role="secondary"]
.Kotlin
----
tasks.register<io.freefair.gradle.plugins.jacoco.tasks.JacocoDump>("dump") {
    address = "localhost"
    port = 6300
    retryCount = 10
    dump = true
    reset = false
    destfile = file("build/dump.exec")
    append = true
}
----
--
