= FreeFair Gradle Plugin Collection
Lars Grefer; Dennis Fricke
:toc: left
:sectnums:
:icons: font
:doctype: book
:source-highlighter: rouge
:sectanchors:
:partnums:
:part-signifier: Module

[colophon]
== About the Documentation

The documentation of the FreeFair Gradle Plugin collection {revnumber} consists of two parts:

- This reference guide
- The Javadoc API

The latest copy of the user guide is available at https://docs.freefair.io/gradle-plugins/current/reference +
and the corresponding javadocs can be found at https://docs.freefair.io/gradle-plugins/current/api.

The source code for the plugins and this documentation can be found at https://github.com/freefair/gradle-plugins

== Installation

All plugins are deployed to the
https://plugins.gradle.org/search?term=io.freefair[Gradle Plugin Portal].

The plugins are grouped in multiple modules, each containing some plugins.
These submodules are described by the different parts of this documentation.

Each plugin can be included using the Plugins DSL
or by referencing its containing module in the `buildscript`-block:

.Using the plugins DSL
--
[source,groovy,subs=attributes+,role="primary"]
.Groovy
----
plugins {
    id "io.freefair.lombok" version "{revnumber}"
}
----
[source,kotlin,subs=attributes+,role="secondary"]
.Kotlin
----
plugins {
    id("io.freefair.lombok") version "{revnumber}"
}
----
--

.Using legacy plugin application
--
[source,groovy,subs=attributes+,role="primary"]
.Groovy
----
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "io.freefair.gradle:lombok-plugin:{revnumber}"
  }
}

apply plugin: "io.freefair.lombok"
----
[source,groovy,subs=attributes+,role="secondary"]
.Kotlin
----
buildscript {
  repositories {
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  dependencies {
    classpath("io.freefair.gradle:lombok-plugin:{revnumber}")
  }
}

apply(plugin = "io.freefair.lombok")
----
--

== System Requirements

=== Gradle

The plugins of version {revnumber} are targeted at Gradle {gradle_version}.

Starting with version 8, the _Major.Minor_ version of the plugins matches those of Gradle itself.

=== Java

Most of the plugins should work all Java versions supported by Gradle {gradle_version}, but some of the included external tools or libraries like Lombok or AJC might have additional constraints.

include::_settings.adoc[]

include::_aspectj.adoc[]

include::_compress.adoc[]

include::_embedded-sass.adoc[]

include::_git.adoc[]

include::_github.adoc[]

include::_jacoco.adoc[]

include::_lombok.adoc[]

include::_maven.adoc[]

include::_maven-plugin.adoc[]

include::_mkdocs.adoc[]

include::_mjml.adoc[]

include::_okhttp.adoc[]

include::_plantuml.adoc[]
